### ISSUE TITLE
Register a class call from another library

### ISSUE THREAD

**Issue by rodmar35** [madsem/klever-skeleton#1]
Hi,

First, thanks for your great skeleton.

I try to add this ACL library [https://github.com/JosephSilber/bouncer](https://github.com/JosephSilber/bouncer) in your AuthMiddleware.php

I success by creating a BouncerServiceProvider and register it.

```
// BouncerServiceProvide.php
namespace Klever\Providers;

use League\Container\ServiceProvider\AbstractServiceProvider;
use Silber\Bouncer\Bouncer;

class BouncerServiceProvider extends AbstractServiceProvider
{
    protected $provides = [
        'bouncer',
    ];

    function register()
    {
        $this->getContainer()
             ->share('bouncer', function () {
                      return Bouncer::create();
             });
    }
}
```

In AuthMiddleware.php, I edit like this : 
```
namespace Klever\Middleware;

use Bouncer;
use Illuminate\Cache\FileStore;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Cache\Repository as cacheRepository;
use Illuminate\Contracts\Cache\Repository as cacheContract;

class AuthMiddleware
{
    function __invoke($request, $response, $next)
    {
        if ( ! container()->get('auth')->verifySession()) {

            session()->flush();

            return redirect(route('auth.login'));
        }
        $acl_folder_path = base_path('storage/acl/');

        $store = new FileStore(new Filesystem, $acl_folder_path);
        $cacheRepository = new CacheContract($store);

        $bouncer = bouncer()->make()->withCache($cacheRepository)->create();
        // ok without cache : $bouncer = bouncer()->make()->create();

        $bouncer->useUserModel(User::class);

        return $next($request, $response);
    }
}
```

But when i want to active Bounce Cache (make()->withCache ...) i'v got this error `Cannot instantiate interface Illuminate\Contracts\Cache\Repository`

I try lot of things but i'm a little lost with register and cache configuration with DI league container

Could you help me please.
Thanks in advance
Rodmar

**Comment by madsem** [comment]
Hey,

you don’t need to add the code in the Auth class.

Simply generate a new ServiceProvider class. There you instantiate the Bouncer object.

Then you register the ServiceProvider you created in ‘config/app.php’ it will be automatically loaded then and available everywhere.

Then you can create a BouncerMiddleWare and register it in your route(s).

**Comment by madsem** [comment]
I had a closer look for you this morning, was only on mobile yesterday.
So it seems you are trying to use the Laravel internal cache, the addon you reference doesn't say in their docs how to use a different cache library or what PSR version etc.

As this is a Slim 3 skeleton, that is using Eloquent, it is not 100% compatible with everything laravel offers. So I'm afraid that is outside the project and I can't help you with that.

But what you need to do is to write a cache bridge, I had something similar so maybe this code here will help you:

```php
<?php

namespace Klever\Cache\Bridges;


use Klever\Cache\Cache;

class MatomoBridge implements \DeviceDetector\Cache\Cache
{

    private $prefix = 'matomo_';

    /**
     * @var Cache
     */
    private $pool;

    /**
     * Cache constructor.
     * @param Cache $pool
     */
    function __construct(Cache $pool)
    {
        $this->pool = $pool;
    }

    /**
     * @inheritDoc
     */
    function fetch($id)
    {
        $item = $this->pool->get($this->prefix.$id);

        return $item ?? false;
    }

    /**
     * @inheritDoc
     */
    function contains($id)
    {
        return !is_null($this->pool->get($this->prefix.$id)) ? true : false;
    }

    /**
     * @inheritDoc
     */
    function save($id, $data, $lifeTime = 0)
    {
        return $this->pool->put($this->prefix.$id, $data);
    }

    /**
     * @inheritDoc
     */
    function delete($id)
    {
        return $this->pool->forget($this->prefix.$id);
    }

    /**
     * @inheritDoc
     */
    function flushAll()
    {
        return $this->pool->forgetPattern($this->prefix . '*');
    }

}
```

**Comment by madsem** [comment]
And here a related issue from Bouncer:
https://github.com/JosephSilber/bouncer/issues/330

Hope this helps to get you on the right track

**Comment by rodmar35** [comment]
Hi madsem,

Thank you for your answer. 

I followed your advice. I created a BouncerServiceProvider class, registered it and added a BouncerMiddleWare.

Finally, i have succeeded using Bouncer's cache without writing a cache bridge. As your skeleton already use Eloquent, it is directly compatible with Bouncer and illuminate cache.

Thanks a lot for your help.
Rodmar

**Comment by madsem** [comment]
Ahh that's great to know, thanks for your feedback :)
