### ISSUE TITLE
Retrieve request Attributes in ViewServiceProvider

### ISSUE THREAD

**Issue by rodmar35** [madsem/klever-skeleton#2]
Hi,

In the ViewServiceProvider.php file, i'm trying to add a twig global variable to store the current route name.

My code : 
```
$routename = $this->getContainer()->get('request')->getAttribute('route')->getName();
$engine->getEnvironment()->addGlobal('current_routename', $routename);
```

Unfortunately Request' Attributes are always empty or null.

Could you help me please.
Thanks
Rodmar

**Comment by madsem** [comment]
Hey sorry for late response, busy.

You can't use it like that, because the service providers are running before the routes are resolved.
See Slim's documentation, they have this exact use case documented: http://www.slimframework.com/docs/v3/cookbook/retrieving-current-route.html
